### PR TITLE
some more suggestions

### PR DESCRIPTION
**Pull request by erdtman**

### CODE REVIEW

**Review by cyberphone — COMMENTED** [review]
That the contents etc. seems language-wise incorrect.
Could we keep the original start of this paragraph?
Note that the contents etc.

shouldn't vanilla rather be plain vanilla?

The rest seems OK although they are more into the personal taste region :)

**Comment by erdtman** [comment]
My bad
"Note that the contents of JWS headers as well as things"
should have been changed to 
"The contents of JWS headers as well as things"
But if you prefer the original one I could live with that too. My thinking was that there was many "note" and I thought this could be written as just stating a fact.

My English is not good enough to say if it should be "vanilla" or "plain vanilla". maybe we could get Bret to chime in. The reason I wanted to change "standard" JWS was that I think this is also standard JWS but used in a specific way. But maybe I missed that goal :)

I know there is lots of personal taste region, I think we can be prestige-less enough to put religion aside. So if you think some of the changes are stupid please say so. My goal was to bring the language closer to the usual IETF language.

**Comment by cyberphone** [comment]
I tried to explain how JWS/CT and JWS relate because it might not be obvious.  How about the following?

{Note that the | The} only dependency between JWS/CT and JWS is JWS string data.
This means that the contents of JWS headers as well as things
related to signature algorithms and cryptographic keys,
are out of scope for this specification, and can be used in the standard way.

**Comment by erdtman** [comment]
I agree that it is a good thing to make clear how JWS/CT and JWS relate. Not sure if it is just me but the word "only" makes me think there is only a small part of JWS that is used in JWS/CT while my understanding is that we use most of JWS (algorithms, headers, signature serialization etc.).

How about something like
JWS/CT makes use of JWS signature creation process, validation process and format in an unaltered way. This means that the contents of JWS headers as well as things related to signature algorithms and cryptographic keys, are out of scope for this specification, and can be used in the standard way.

**Comment by cyberphone** [comment]
> JWS/CT makes use of JWS signature creation process, validation process and _format in an unaltered way_. This means that the contents of JWS headers as well as things related to signature algorithms and cryptographic keys, are out of scope for this specification, and can be used in the standard way

This sounds great but is it really true?   What I'm thinking of is JWS/CT's use of Appendix F which is not a part of the core JWS standard. 

**One could say:**
With the exception of JWS/CT's reliance on the detached mode described in `url,` JWS ' signature creation process, validation process, and format is used in an <em>unaltered way</em>. This means that the contents of JWS headers as well as things related to signature algorithms and cryptographic keys, are out of scope for this specification.

Comment: I hardly ever use the ' notation in texts like this but I didn't see how to to get rid of it without creating unnecessary quirky lines.

**Another try:**
With the exception of the reliance on the detached mode described in `url,` JWS/CT does not alter the JWS signature creation process, validation process, or format. This means that the contents of JWS headers as well as things related to signature algorithms and cryptographic keys, are out of scope for this specification.

**Comment by erdtman** [comment]
I like the last one, I´ll update the PR with that

**Comment by erdtman** [comment]
pushed an update, have a look to see if you think it is acceptable.

**Pull request merged**
